name: confluence_ai_app
description: A Flutter app that interacts with Confluence data using AI.

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
 